// =============================================================================
// HIS & EMR UI AUTOMATION REPLAY RECIPE - AUTO GENERATED BY HIS UI WRAPPER
// Session: 20260918_163401 | Created: 2026-09-18 16:47:29
// =============================================================================
using System;
using System.Diagnostics;
using System.Threading;
using System.Windows.Automation;

namespace HisUiAutomation
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Khởi động kịch bản Replay tự động...");
            AutomationElement root = AutomationElement.RootElement;

            // -------------------------------------------------------------
            // Bước 1: [HIS] [Click] Left on 'Data Panel' () in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 0ms | Tọa độ màn hình: (392, 757)
            // -------------------------------------------------------------
            try
            {
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Data Panel", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 2: [HIS] (⏱️ chờ 1,4s) [Click] Left on 'Chọn phòng' () in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 1395ms | Tọa độ màn hình: (83, 14)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1395ms)...");
                Thread.Sleep(1395);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Chọn phòng", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 3: [HIS] (⏱️ chờ 3,8s) [Click] Left on '' (526252) in 'Chọn phòng'
            // Thời gian chờ tải thực tế: 3757ms | Tọa độ màn hình: (585, 340)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (3757ms)...");
                Thread.Sleep(3757);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "526252", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 4: [HIS] (⏱️ chờ 2,2s) [Type] "tieeur" into '' (526252)
            // Thời gian chờ tải thực tế: 2236ms | Tọa độ màn hình: (960, 338)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (2236ms)...");
                Thread.Sleep(2236);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "526252", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("tieeur");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 5: [HIS] (⏱️ chờ 707ms) [Click] Left on 'Chọn row 1' () in 'Chọn phòng'
            // Thời gian chờ tải thực tế: 707ms | Tọa độ màn hình: (551, 443)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (707ms)...");
                Thread.Sleep(707);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Chọn row 1", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 6: [HIS] (⏱️ chờ 1,1s) [Click] Left on 'Chọn (Ctrl S)' (btnChoice) in 'Chọn phòng'
            // Thời gian chờ tải thực tế: 1065ms | Tọa độ màn hình: (1322, 770)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1065ms)...");
                Thread.Sleep(1065);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "btnChoice", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 7: [HIS] (⏱️ chờ 6,7s) [Click] Left on 'Phòng Tiểu Phẫu (Nhà Q) (Khoa Chấn Thương Chỉnh Hình & CS)' () in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 6683ms | Tọa độ màn hình: (488, 37)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Phòng Tiểu Phẫu (Nhà Q) (Khoa Chấn Thương Chỉnh Hình & CS)", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 8: [HIS] (⏱️ chờ 3,5s) [Click] Left on 'Xử lý yêu cầu khám/cls/pttt' () in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 3525ms | Tọa độ màn hình: (43, 101)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (3525ms)...");
                Thread.Sleep(3525);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Xử lý yêu cầu khám/cls/pttt", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 9: [HIS] (⏱️ chờ 28,1s) [Click] Left on 'Tên bệnh nhân row 1' () in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 28113ms | Tọa độ màn hình: (360, 374)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Tên bệnh nhân row 1", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 10: [HIS] (⏱️ chờ 8,5s) [Click] Left on 'Editing control' (1640664) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 8522ms | Tọa độ màn hình: (360, 374)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "1640664", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 11: [HIS] [DoubleClick] Left on 'Editing control' (1640664) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 78ms | Tọa độ màn hình: (360, 374)
            // -------------------------------------------------------------
            try
            {
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "1640664", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 12: [HIS] (⏱️ chờ 28,2s) [Click] Left on 'Thay băng điều trị vết thương mạn tính' (2230824) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 28222ms | Tọa độ màn hình: (726, 473)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2230824", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 13: [HIS] (⏱️ chờ 4,2s) [Type] "rust ddinh " into 'Thay băng điều trị vết thương mạn tính' (2230824)
            // Thời gian chờ tải thực tế: 4243ms | Tọa độ màn hình: (774, 484)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (4243ms)...");
                Thread.Sleep(4243);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2230824", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("rust ddinh ");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 14: [HIS] (⏱️ chờ 3,1s) [Type] "khx ngons chana " into 'rút đinh ' (2230824)
            // Thời gian chờ tải thực tế: 3070ms | Tọa độ màn hình: (774, 484)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (3070ms)...");
                Thread.Sleep(3070);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2230824", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("khx ngons chana ");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 15: [HIS] (⏱️ chờ 5,5s) [Type] "phair " into 'rút đinh khx ngón chân ' (2230824)
            // Thời gian chờ tải thực tế: 5466ms | Tọa độ màn hình: (774, 484)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2230824", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("phair ");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 16: [HIS] (⏱️ chờ 3,7s) [Click] Left on 'rút đinh khx ngón chân phải ' (2230824) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 3708ms | Tọa độ màn hình: (674, 476)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (3708ms)...");
                Thread.Sleep(3708);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2230824", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 17: [HIS] (⏱️ chờ 679ms) [Key] Ctrl+C in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 679ms | Tọa độ màn hình: (774, 484)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (679ms)...");
                Thread.Sleep(679);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2230824", 5000);
                if (target != null)
                {
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 18: [HIS] (⏱️ chờ 3,8s) [Key] Ctrl+V in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 3799ms | Tọa độ màn hình: (774, 484)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (3799ms)...");
                Thread.Sleep(3799);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2230824", 5000);
                if (target != null)
                {
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 19: [HIS] [Click] Left on 'rút đinh khx ngón chân phải ' (1378524) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 0ms | Tọa độ màn hình: (576, 559)
            // -------------------------------------------------------------
            try
            {
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "1378524", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 20: [HIS] (⏱️ chờ 2,7s) [Click] Left on 'Close' () in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 2703ms | Tọa độ màn hình: (1534, 244)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (2703ms)...");
                Thread.Sleep(2703);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Close", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 21: [HIS] (⏱️ chờ 1,5s) [Click] Left on 'PTTT_PRIORITY_CODE row 1' () in ''
            // Thời gian chờ tải thực tế: 1470ms | Tọa độ màn hình: (1485, 283)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1470ms)...");
                Thread.Sleep(1470);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "PTTT_PRIORITY_CODE row 1", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 22: [HIS] (⏱️ chờ 1,9s) [Click] Left on '' (2557146) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 1937ms | Tọa độ màn hình: (1335, 515)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1937ms)...");
                Thread.Sleep(1937);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 23: [HIS] (⏱️ chờ 5,3s) [Type] "ast sats khuaanr " into '' (2557146)
            // Thời gian chờ tải thực tế: 5313ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("ast sats khuaanr ");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 24: [HIS] (⏱️ chờ 4,3s) [Type] "trari toan" into 'sát khuẩn ' (2557146)
            // Thời gian chờ tải thực tế: 4332ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (4332ms)...");
                Thread.Sleep(4332);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("trari toan");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 25: [HIS] [Key] Enter in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 62ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 26: [HIS] (⏱️ chờ 3,3s) [Type] "tee goocs chi" into 'sát khuẩn trải toan
' (2557146)
            // Thời gian chờ tải thực tế: 3296ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (3296ms)...");
                Thread.Sleep(3296);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("tee goocs chi");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 27: [HIS] [Key] Enter in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 74ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 28: [HIS] (⏱️ chờ 3,9s) [Type] "rachj rada nhor " into 'sát khuẩn trải toan
tê gốc chi
' (2557146)
            // Thời gian chờ tải thực tế: 3936ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (3936ms)...");
                Thread.Sleep(3936);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("rachj rada nhor ");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 29: [HIS] [Key] Enter in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 161ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 30: [HIS] (⏱️ chờ 7,3s) [Type] "boojc looj ddaauf xa ddinh " into 'sát khuẩn trải toan
tê gốc chi
rạch da nhỏ 
' (2557146)
            // Thời gian chờ tải thực tế: 7291ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("boojc looj ddaauf xa ddinh ");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 31: [HIS] (⏱️ chờ 4,5s) [Type] "kinrisschnerr" into 'sát khuẩn trải toan
tê gốc chi
rạch da nhỏ 
bộc lộ đầu xa đinh ' (2557146)
            // Thời gian chờ tải thực tế: 4497ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (4497ms)...");
                Thread.Sleep(4497);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("kinrisschnerr");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 32: [HIS] [Key] Enter in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 64ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 33: [HIS] (⏱️ chờ 6,8s) [Type] "keoj p " into 'sát khuẩn trải toan
tê gốc chi
rạch da nhỏ 
bộc lộ đầu xa đinh krischner
' (2557146)
            // Thời gian chờ tải thực tế: 6835ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("keoj p ");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 34: [HIS] (⏱️ chờ 3,1s) [Type] "laasy didnh " into 'sát khuẩn trải toan
tê gốc chi
rạch da nhỏ 
bộc lộ đầu xa đinh krischner
kẹp ' (2557146)
            // Thời gian chờ tải thực tế: 3132ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (3132ms)...");
                Thread.Sleep(3132);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("laasy didnh ");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 35: [HIS] [Key] Enter in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 62ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 36: [HIS] (⏱️ chờ 3,0s) [Type] "laasy ddur 2 didnh" into 'sát khuẩn trải toan
tê gốc chi
rạch da nhỏ 
bộc lộ đầu xa đinh krischner
kẹp lấy đinh 
' (2557146)
            // Thời gian chờ tải thực tế: 2990ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (2990ms)...");
                Thread.Sleep(2990);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("laasy ddur 2 didnh");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 37: [HIS] [Key] Enter in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 70ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 38: [HIS] (⏱️ chờ 2,3s) [Type] "sast khuanar" into 'sát khuẩn trải toan
tê gốc chi
rạch da nhỏ 
bộc lộ đầu xa đinh krischner
kẹp lấy đinh 
lấy đủ 2 đinh
' (2557146)
            // Thời gian chờ tải thực tế: 2267ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (2267ms)...");
                Thread.Sleep(2267);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("sast khuanar");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 39: [HIS] [Key] Enter in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 62ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 40: [HIS] (⏱️ chờ 3,1s) [Type] "bawng veest moor " into 'sát khuẩn trải toan
tê gốc chi
rạch da nhỏ 
bộc lộ đầu xa đinh krischner
kẹp lấy đinh 
lấy đủ 2 đinh
sát khuẩn
' (2557146)
            // Thời gian chờ tải thực tế: 3100ms | Tọa độ màn hình: (1550, 561)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (3100ms)...");
                Thread.Sleep(3100);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2557146", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("bawng veest moor ");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 41: [HIS] (⏱️ chờ 1,4s) [Click] Left on '' (3212878) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 1393ms | Tọa độ màn hình: (1228, 688)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1393ms)...");
                Thread.Sleep(1393);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "3212878", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 42: [HIS] (⏱️ chờ 1,7s) [Type] "hdc" into '' (3212878)
            // Thời gian chờ tải thực tế: 1679ms | Tọa độ màn hình: (1339, 686)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1679ms)...");
                Thread.Sleep(1679);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "3212878", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("hdc");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 43: [HIS] (⏱️ chờ 3,2s) [Click] Left on '' (1968784) in ''
            // Thời gian chờ tải thực tế: 3155ms | Tọa độ màn hình: (1397, 728)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (3155ms)...");
                Thread.Sleep(3155);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "1968784", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 44: [HIS] (⏱️ chờ 1,0s) [Click] Left on '' (2098482) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 1000ms | Tọa độ màn hình: (1659, 686)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1000ms)...");
                Thread.Sleep(1000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2098482", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 45: [HIS] (⏱️ chờ 1,7s) [Type] "hdc" into '' (2098482)
            // Thời gian chờ tải thực tế: 1664ms | Tọa độ màn hình: (1756, 686)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1664ms)...");
                Thread.Sleep(1664);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2098482", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("hdc");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 46: [HIS] [Click] Left on 'Tên đăng nhập row 0' () in ''
            // Thời gian chờ tải thực tế: 93ms | Tọa độ màn hình: (1648, 731)
            // -------------------------------------------------------------
            try
            {
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Tên đăng nhập row 0", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 47: [HIS] (⏱️ chờ 1,9s) [Click] Left on 'Editing control' (1378844) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 1882ms | Tọa độ màn hình: (1031, 765)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1882ms)...");
                Thread.Sleep(1882);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "1378844", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 48: [HIS] (⏱️ chờ 2,2s) [Type] "saam" into '' (658204)
            // Thời gian chờ tải thực tế: 2176ms | Tọa độ màn hình: (1154, 758)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (2176ms)...");
                Thread.Sleep(2176);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "658204", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("saam");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 49: [HIS] (⏱️ chờ 733ms) [Click] Left on 'Họ tên row 1' () in ''
            // Thời gian chờ tải thực tế: 733ms | Tọa độ màn hình: (1205, 480)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (733ms)...");
                Thread.Sleep(733);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Họ tên row 1", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 50: [HIS] (⏱️ chờ 1,4s) [Click] Left on 'Editing control' (854812) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 1354ms | Tọa độ màn hình: (993, 780)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1354ms)...");
                Thread.Sleep(1354);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "854812", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 51: [HIS] (⏱️ chờ 5,7s) [Type] "minh" into '' (854812)
            // Thời gian chờ tải thực tế: 5713ms | Tọa độ màn hình: (1154, 778)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "854812", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("minh");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 52: [HIS] (⏱️ chờ 2,6s) [Click] Left on 'Họ tên row 6' () in ''
            // Thời gian chờ tải thực tế: 2571ms | Tọa độ màn hình: (1350, 595)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (2571ms)...");
                Thread.Sleep(2571);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Họ tên row 6", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 53: [HIS] (⏱️ chờ 10,0s) [Click] Left on 'Tủ trực' (btnTuTruc) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 10000ms | Tọa độ màn hình: (89, 991)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "btnTuTruc", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 54: [HIS] (⏱️ chờ 41,6s) [Click] Left on 'Close' () in 'Xuất thuốc tủ trực (phòng khám)'
            // Thời gian chờ tải thực tế: 41562ms | Tọa độ màn hình: (1189, 33)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Close", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 55: [HIS] (⏱️ chờ 1,2s) [Click] Left on 'Mark' () in ''
            // Thời gian chờ tải thực tế: 1210ms | Tọa độ màn hình: (624, 52)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1210ms)...");
                Thread.Sleep(1210);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Mark", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 56: [HIS] (⏱️ chờ 956ms) [Click] Left on 'Data Panel' () in 'Xuất thuốc tủ trực (phòng khám)'
            // Thời gian chờ tải thực tế: 956ms | Tọa độ màn hình: (579, 497)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (956ms)...");
                Thread.Sleep(956);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Data Panel", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 57: [HIS] (⏱️ chờ 5,3s) [Click] Left on 'Chọn thuốc - vật tư' (7800386) in 'Xuất thuốc tủ trực (phòng khám)'
            // Thời gian chờ tải thực tế: 5288ms | Tọa độ màn hình: (140, 205)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "7800386", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 58: [HIS] (⏱️ chờ 3,8s) [Click] Left on '' () in 'Xuất thuốc tủ trực (phòng khám)'
            // Thời gian chờ tải thực tế: 3842ms | Tọa độ màn hình: (314, 207)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (3842ms)...");
                Thread.Sleep(3842);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 59: [HIS] (⏱️ chờ 3,4s) [Click] Left on '' (7800386) in 'Xuất thuốc tủ trực (phòng khám)'
            // Thời gian chờ tải thực tế: 3392ms | Tọa độ màn hình: (205, 211)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (3392ms)...");
                Thread.Sleep(3392);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "7800386", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 60: [HIS] (⏱️ chờ 2,1s) [Type] "lido" into '' (7800386)
            // Thời gian chờ tải thực tế: 2065ms | Tọa độ màn hình: (204, 208)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (2065ms)...");
                Thread.Sleep(2065);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "7800386", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("lido");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 61: [HIS] (⏱️ chờ 779ms) [Click] Left on '' (gridControlMediMaty) in ''
            // Thời gian chờ tải thực tế: 779ms | Tọa độ màn hình: (201, 250)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (779ms)...");
                Thread.Sleep(779);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "gridControlMediMaty", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 62: [HIS] (⏱️ chờ 1,7s) [Click] Left on '' (6292914) in 'Xuất thuốc tủ trực (phòng khám)'
            // Thời gian chờ tải thực tế: 1668ms | Tọa độ màn hình: (521, 240)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1668ms)...");
                Thread.Sleep(1668);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "6292914", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 63: [HIS] (⏱️ chờ 6,8s) [Type] "1" into '' (6292914)
            // Thời gian chờ tải thực tế: 6751ms | Tọa độ màn hình: (505, 239)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "6292914", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("1");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 64: [HIS] (⏱️ chờ 962ms) [Click] Left on '28' (6292778) in 'Xuất thuốc tủ trực (phòng khám)'
            // Thời gian chờ tải thực tế: 962ms | Tọa độ màn hình: (174, 236)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (962ms)...");
                Thread.Sleep(962);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "6292778", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 65: [HIS] (⏱️ chờ 1,8s) [Type] "1" into '28' (6292778)
            // Thời gian chờ tải thực tế: 1761ms | Tọa độ màn hình: (152, 239)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1761ms)...");
                Thread.Sleep(1761);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "6292778", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("1");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 66: [HIS] (⏱️ chờ 2,6s) [Click] Left on 'Ngày tiêm 1 ống buổi trưa' (2361936) in 'Xuất thuốc tủ trực (phòng khám)'
            // Thời gian chờ tải thực tế: 2552ms | Tọa độ màn hình: (345, 300)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (2552ms)...");
                Thread.Sleep(2552);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2361936", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 67: [HIS] [DoubleClick] Left on 'Ngày tiêm 1 ống buổi trưa' (2361936) in 'Xuất thuốc tủ trực (phòng khám)'
            // Thời gian chờ tải thực tế: 197ms | Tọa độ màn hình: (345, 300)
            // -------------------------------------------------------------
            try
            {
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2361936", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 68: [HIS] (⏱️ chờ 531ms) [Click] Left on 'Ngày tiêm 1 ống buổi trưa' (2361936) in 'Xuất thuốc tủ trực (phòng khám)'
            // Thời gian chờ tải thực tế: 531ms | Tọa độ màn hình: (344, 300)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (531ms)...");
                Thread.Sleep(531);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2361936", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 69: [HIS] (⏱️ chờ 14,7s) [Type] "tee duwois da" into 'Ngày tiêm 1 ống buổi trưa' (2361936)
            // Thời gian chờ tải thực tế: 14670ms | Tọa độ màn hình: (467, 299)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "2361936", 5000);
                if (target != null)
                {
                    object valPattern;
                    if (target.TryGetCurrentPattern(ValuePattern.Pattern, out valPattern))
                        ((ValuePattern)valPattern).SetValue("tee duwois da");
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 70: [HIS] [Click] Left on 'Bổ sung
(Ctrl A)' (btnAdd) in 'Xuất thuốc tủ trực (phòng khám)'
            // Thời gian chờ tải thực tế: 417ms | Tọa độ màn hình: (1055, 280)
            // -------------------------------------------------------------
            try
            {
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "btnAdd", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 71: [HIS] (⏱️ chờ 7,8s) [Click] Left on 'Lưu (Ctrl S)' (btnSave) in 'Xuất thuốc tủ trực (phòng khám)'
            // Thời gian chờ tải thực tế: 7775ms | Tọa độ màn hình: (679, 1016)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "btnSave", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 72: [HIS] (⏱️ chờ 11,6s) [Click] Left on 'Close' (Close) in 'Xuất thuốc tủ trực (phòng khám)'
            // Thời gian chờ tải thực tế: 11625ms | Tọa độ màn hình: (1898, 9)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "Close", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 73: [HIS] (⏱️ chờ 28,9s) [Click] Left on '' (chkSign) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 28914ms | Tọa độ màn hình: (700, 992)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "chkSign", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 74: [HIS] (⏱️ chờ 1,8s) [Click] Left on 'Lưu
(Ctrl S)' (btnSave) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 1833ms | Tọa độ màn hình: (1123, 999)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1833ms)...");
                Thread.Sleep(1833);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "btnSave", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 75: [HIS] (⏱️ chờ 19,4s) [Click] Left on 'Có' (6) in 'Thông báo'
            // Thời gian chờ tải thực tế: 19444ms | Tọa độ màn hình: (1020, 610)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "6", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 76: [HIS] (⏱️ chờ 21,3s) [Click] Left on 'Ký' () in 'Văn bản điện tử'
            // Thời gian chờ tải thực tế: 21296ms | Tọa độ màn hình: (201, 26)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Ký", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 77: [HIS] (⏱️ chờ 3,0s) [Click] Left on '' (DocumentViewer) in 'Văn bản điện tử'
            // Thời gian chờ tải thực tế: 2982ms | Tọa độ màn hình: (1167, 909)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (2982ms)...");
                Thread.Sleep(2982);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "DocumentViewer", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 78: [HIS] (⏱️ chờ 413,1s) [Click] Left on 'Kết thúc 
xử lý (Ctrl E)' (btnFinish) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 413090ms | Tọa độ màn hình: (1701, 999)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "btnFinish", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 79: [HIS] (⏱️ chờ 1,2s) [Click] Left on 'Có' (6) in 'Thông báo'
            // Thời gian chờ tải thực tế: 1247ms | Tọa độ màn hình: (1013, 606)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (1247ms)...");
                Thread.Sleep(1247);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "6", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 80: [HIS] (⏱️ chờ 5,8s) [Click] Left on '' () in ''
            // Thời gian chờ tải thực tế: 5770ms | Tọa độ màn hình: (1073, 482)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 81: [HIS] (⏱️ chờ 7,6s) [Click] Left on '' (tabControlMain) in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 7632ms | Tọa độ màn hình: (1357, 151)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (5000ms)...");
                Thread.Sleep(5000);
                var target = FindElementWithWait(root, AutomationElement.AutomationIdProperty, "tabControlMain", 5000);
                if (target != null)
                {
                    object invPattern;
                    if (target.TryGetCurrentPattern(InvokePattern.Pattern, out invPattern))
                        ((InvokePattern)invPattern).Invoke();
                }
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 82: [HIS] (⏱️ chờ 603ms) [Click] Left on 'Buồng bệnh Khoa Chấn thương Chỉnh hình và Cột sống' () in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 603ms | Tọa độ màn hình: (221, 36)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (603ms)...");
                Thread.Sleep(603);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Buồng bệnh Khoa Chấn thương Chỉnh hình và Cột sống", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            // -------------------------------------------------------------
            // Bước 83: [HIS] (⏱️ chờ 2,2s) [Click] Left on 'Buồng bệnh' () in 'Hotline CNTT Hà Nội: 0949.415.885   Hotline CNTT Ninh Bình: 0869744388'
            // Thời gian chờ tải thực tế: 2162ms | Tọa độ màn hình: (37, 91)
            // -------------------------------------------------------------
            try
            {
                Console.WriteLine("Chờ tải dữ liệu (2162ms)...");
                Thread.Sleep(2162);
                var target = FindElementWithWait(root, AutomationElement.NameProperty, "Buồng bệnh", 5000);
                Thread.Sleep(300);
            }
            catch (Exception ex) { Console.WriteLine("Lỗi bước: " + ex.Message); }

            Console.WriteLine("Replay Hoàn Tất Thành Công.");
        }

        private static AutomationElement FindElementWithWait(AutomationElement root, AutomationProperty prop, string val, int timeoutMs)
        {
            var cond = new PropertyCondition(prop, val);
            var sw = Stopwatch.StartNew();
            while (sw.ElapsedMilliseconds < timeoutMs)
            {
                var el = root.FindFirst(TreeScope.Descendants, cond);
                if (el != null) return el;
                Thread.Sleep(200);
            }
            return null;
        }
    }
}
